[theme]
base = "dark"
primaryColor = "#00E5FF"
backgroundColor = "#030816"
secondaryBackgroundColor = "#0F172A"
textColor = "#E2E8F0"
font = "sans serif"

[server]
headless = true

[logger]
level = "error"